---
output: 
  pdf_document:
    latex_engine: xelatex
    template: template/cv.tex
geometry: margin=1in

title: "CV"
author: "Luke Lewandowski"
jobtitle: Head of Development and Quality Assurance
address: "Sydney, Australia"
fontawesome: yes
email: luke@lewandowskis.com
linkedin: "luke-lewandowski"
github: "lemining"
phone: "+61-403-018-388" 
updated: no

keywords: software development, manger, agile, scrum, testing, quality assurance

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

#summary
I'm a goal oriented professional with a consistent record of exceeding performance expectations. 
Most recently I have been involved in digital transformations of large non-digital businesses to fulfil on their digital strategies resulting in extra revenue streams as well as increasing digital awareness throughout the business.

Those opportunities involved building high performance development and quality assurance teams from the ground up. Introducing processes and educating the business on how to become digital centric. 
I'm a strong believer in a flat management structure with minimal or no title as I believe that every individual brings something to the team regardless of their years of experience, education, gender or race.

I live by "open, honest and transparent" core values as I believe they are fundamental for any team to succeed.

My passion is still building - I spent my free time building software, restoring old motorcycles, renovating or building furniture.

#employment
**Head of Dev & QA** @ Seven West Media, Sydney \hfill _12/2016-Current_

> Seven is a major Australian commercial free to air television network with the largest market share of viewers in Australia across traditional broadcasters.

> I have been responsible to building development and quality assurance department as well as processes to deliver what at the time the largest digital undertaking from Seven – 7plus product. 

> Currently my department is the largest out of Product and Technology with 20+ individuals working on development of core services (microservices), platforms such as web, iOS, Android, HbbTV, AndroidTV, AppleTV with more platforms being investigated and developed as required.

*Digital Development Director @ Pacific Magazines, Sydney* \hfill _09/2015-12/2016_

> Pacific Magazines is leading publisher of Australia’s bestselling magazines such as Better Homes & Gardens and nation’s leading fashion brand – Marie Claire.
I have joined Pacific Magazines to migrate their digital portfolio away from multiple outsourcing vendors, reconcile and build inhouse development team.

> My team has delivered over 16 magazines websites all in a white label platform purpose build to manage Pacific’s unique content. Also, as a diversification exercise – the business invested in several ventures that we delivered in-house – such as bhgshop.com.au, pepperleaf.com.au (home food delivery with recipes), BeautyCrew.com.au (cosmetics reviews and content).

> **Highlights**

> *	All outsourced platforms were brought and delivered in-house.
> * Pacific Mags continue to deliver great products based on our original platform.

# EDUCATION

*Yale University*, Ph.D. Mathematics \hfill 1934

*Yale University*, M.S. Mathematics \hfill 1930

*Vassar College*, B.S. Mathematics & Physics \hfill 1928

# EMPLOYMENT

*United States Naval Reserve:*

 > Naval Reserve Midshipmen's School \hfill 1943--1944

*Bureau of Ships Computation Project (Harvard):*

 > Research Fellow \hfill 1945-1949
 > Lieutenant, Jr Grade \hfill 1944
 
*Eckert–Mauchly Computer Corporation:*

 >  Senior Mathematician \hfill 1949-–1967

*Navy Programming Languages Group, Navy Office of Information Systems Planning:*

 > Director (and promoted to Captain) \hfill 1967--1977  

# TEACHING

*Associate Professor, Mathematics, Vassar* \hfill 1931--1941

> Teach students about math, began career in programming and largely developed design and implementation of a computer compiler.
  
*Director, Navy Programming Languages Group* \hfill 1967--1977

> She developed validation software for COBOL and its compiler as part of a COBOL standardization program for the entire Navy. Hopper advocated for the Defense Department to replace large, centralized systems with networks of small, distributed computers. Any user on any computer node could access common databases located on the network. She developed the implementation of standards for testing computer systems and components, most significantly for early programming languages such as FORTRAN and COBOL. The Navy tests for conformance to these standards led to significant convergence among the programming language dialects of the major computer vendors. In the 1980s, these tests (and their official administration) were assumed by the National Bureau of Standards (NBS), known today as the National Institute of Standards and Technology (NIST). (Source: https://en.wikipedia.org/wiki/Grace_Hopper)

# PUBLICATIONS

## **Journal Articles**

G. M. Hopper and O. Ore. 1934. "*New types of irreducibility criteria*." Bull. Amer. Math. Soc. 40 (216). 



## **Books**

Beyer, Kurt W. 2009. *Grace Hopper and the Invention of the Information Age*. Cambridge, Massachusetts: MIT Press. ISBN 978-0-262-01310-9.

Williams, Kathleen Broome. 2004. *Grace Hopper: Admiral of the Cyber Sea* (1st ed.). Annapolis, Maryland: Naval Institute Press. ISBN 978-1-55750-952-9.

# PUBLIC MEDIA

"Nano-seconds" lecture by Grace Hopper. https://www.youtube.com/watch?v=JEpsKnWZrJ8


# AWARDS

**1964**  *Society of Women Engineers Achievement Award*, the Society’s highest honor, “In recognition of her significant contributions to the burgeoning computer industry as an engineering manager and originator of automatic programming systems.”

**1969**  *Data Processing Management Association Man of the Year* (now called the Distinguished Information Sciences Award)

**1973** *Distinguished Fellow of the British Computer Society*. First American and the first woman of any nationality to be given award.

**1982** *American Association of University Women Achievement Award*

**1987** *Computer History Museum Fellow Award Recipient* First to receive this award, for contributions to the development of programming languages, for standardization efforts, and for lifelong naval service.

**1991**: *National Medal of Technology*

**1996**: *USS Hopper (DDG-70) was launched*. Nicknamed Amazing Grace, it is on a very short list of U.S. military vessels named after women.

**2009**: The Department of Energy's National Energy Research Scientific Computing Center named its flagship system "Hopper"

**2016**: Posthumously awarded a *Presidential Medal of Freedom* for her accomplishments in the field of computer science

